# Override para desenvolvimento local
# Este arquivo é automaticamente carregado pelo docker-compose
# e permite personalização sem modificar o arquivo principal

services:
  mysql_db:
    environment:
      - TZ=America/Sao_Paulo
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m

  postgres_db:
    environment:
      - TZ=America/Sao_Paulo
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m

  sqlserver_db:
    environment:
      - TZ=America/Sao_Paulo
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g